################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Português ##################
[pt-br]
languageName = "Português"
languageCode = "pt-br"
contentDir = "content/portuguese"
weight = 2